import fs from "fs";
import path from "path";

export type Category = "commercial" | "residential" | "shop" | "about" | "renderings";

export const CATEGORIES: Category[] = ["commercial", "residential", "shop", "about", "renderings"];

const IMG_RE = /\.(jpe?g|png|webp|gif)$/i;

function publicDir(category: Category) {
  return path.resolve("./public/images", category);
}

function orderFile(category: Category) {
  return path.join(publicDir(category), "order.json");
}

function listOnDisk(category: Category): string[] {
  const dir = publicDir(category);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f: string) => IMG_RE.test(f)).sort();
}

interface CropRect {
  x: number;
  y: number;
  scale: number;
}

interface OrderFile {
  order: string[];
  hidden?: string[];
  crop?: Record<string, CropRect>;
}

function loadOrder(category: Category): OrderFile {
  const f = orderFile(category);
  if (!fs.existsSync(f)) return { order: [], hidden: [] };
  try {
    const raw = JSON.parse(fs.readFileSync(f, "utf-8"));
    const cropRaw = raw && typeof raw.crop === "object" && raw.crop !== null && !Array.isArray(raw.crop)
      ? raw.crop
      : {};
    const crop: Record<string, CropRect> = {};
    for (const [file, value] of Object.entries(cropRaw)) {
      if (value && typeof value === "object") {
        const x = Number((value as any).x);
        const y = Number((value as any).y);
        const scale = Number((value as any).scale);
        if (!Number.isNaN(x) && !Number.isNaN(y) && !Number.isNaN(scale)) {
          crop[file] = { x, y, scale };
        }
      }
    }
    return {
      order: Array.isArray(raw.order) ? raw.order : [],
      hidden: Array.isArray(raw.hidden) ? raw.hidden : [],
      crop,
    };
  } catch {
    return { order: [], hidden: [] };
  }
}

export interface GalleryState {
  visible: string[]; // ordered list of /images/{cat}/{file}
  hidden: string[];
  files: string[]; // all files on disk (filename only)
  crop: Record<string, CropRect | undefined>;
}

export function getGallery(category: Category): GalleryState {
  const onDisk = listOnDisk(category);
  const { order, hidden = [], crop = {} } = loadOrder(category);
  const onDiskSet = new Set(onDisk);
  const hiddenSet = new Set(hidden.filter((h) => onDiskSet.has(h)));

  // Start with saved order, dropping any files that no longer exist
  const ordered = order.filter((f) => onDiskSet.has(f));
  const seen = new Set(ordered);
  // Append any new files not yet in the manifest (at the end)
  for (const f of onDisk) if (!seen.has(f)) ordered.push(f);

  const visible = ordered
    .filter((f) => !hiddenSet.has(f))
    .map((f) => `/images/${category}/${f}`);
  const hiddenList = ordered
    .filter((f) => hiddenSet.has(f))
    .map((f) => `/images/${category}/${f}`);
  const cropMap = Object.fromEntries(onDisk.map((file) => [file, crop[file]]));

  return { visible, hidden: hiddenList, files: onDisk, crop: cropMap };
}

// --- Optimized variants (generated by scripts/generate_web_images.mjs) ---
// _web  = max 1200px WebP for gallery grids
// _full = max 2000px WebP for lightbox / click-through views
// Falls back to the original URL at build time if the variant doesn't exist,
// so pages never break when a variant hasn't been generated yet.
export type Variant = "_web" | "_full";

export function variantUrl(originalUrl: string, variant: Variant): string {
  const m = originalUrl.match(/^\/images\/([^/]+)\/([^/]+)$/);
  if (!m) return originalUrl;
  const [, category, file] = m;
  const base = file.replace(/\.[^.]+$/, "");
  const rel = path.join("./public/images", category, variant, `${base}.webp`);
  if (!fs.existsSync(path.resolve(rel))) return originalUrl;
  return `/images/${category}/${variant}/${base}.webp`;
}

export function saveOrder(category: Category, order: string[], hidden: string[], crop: Record<string, CropRect> = {}) {
  const dir = publicDir(category);
  if (!fs.existsSync(dir)) throw new Error(`No such category: ${category}`);
  const onDisk = new Set(listOnDisk(category));
  const cleanOrder = order.filter((f) => onDisk.has(f));
  const cleanHidden = hidden.filter((f) => onDisk.has(f));
  const cleanCrop: Record<string, CropRect> = {};
  for (const [file, value] of Object.entries(crop)) {
    if (!onDisk.has(file)) continue;
    if (!value || typeof value !== 'object') continue;
    const x = Number((value as any).x);
    const y = Number((value as any).y);
    const scale = Number((value as any).scale);
    if (Number.isNaN(x) || Number.isNaN(y) || Number.isNaN(scale)) continue;
    if (scale === 1 && x === 50 && y === 50) continue;
    cleanCrop[file] = { x, y, scale };
  }
  const payload = { order: cleanOrder, hidden: cleanHidden, crop: cleanCrop };
  fs.writeFileSync(orderFile(category), JSON.stringify(payload, null, 2), "utf-8");
  return payload;
}
